name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - run: pip install --upgrade cmake
    - run: mkdir build && cd build && cmake .. -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build
  
  build-macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - run: mkdir build && cd build && cmake .. -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build
